const KEY="bluewave_swimming_v1";
const ADMIN_USER="shreen", ADMIN_PASS="2908";
function login(e){e.preventDefault();const u=document.getElementById("loginUser").value,p=document.getElementById("loginPass").value;if(u===ADMIN_USER&&p===ADMIN_PASS){sessionStorage.setItem("bw_admin","1");document.getElementById("loginScreen").style.display="none";document.querySelectorAll(".admin-only").forEach(x=>x.style.display="block");toast("Welcome, Shreen");updateAdminUI();go("dashboard")}else document.getElementById("loginError").textContent="Incorrect username or password."}
function enterVisitor(){sessionStorage.setItem("bw_visitor","1");document.getElementById("loginScreen").style.display="none";go("public")}
function logout(){sessionStorage.removeItem("bw_admin");location.reload()}
function checkAccess(){if(sessionStorage.getItem("bw_admin")==="1"){document.getElementById("loginScreen").style.display="none";return}document.querySelectorAll(".page:not(#public)").forEach(x=>x.classList.remove("active"));document.getElementById("public").classList.add("active");document.querySelectorAll(".nav").forEach(x=>{x.style.display=x.dataset.page==="public"?"block":"none"});document.getElementById("modeBtn").style.display="none"}

const defaultData={months:["August 2026"],coaches:[
{id:1,name:"Coach Ahmed Hassan",phone:"0100 123 4567",specialty:"Competitive Swimming",bio:"Freestyle and butterfly specialist.",rating:4.9},
{id:2,name:"Coach Sara Ali",phone:"0111 234 5678",specialty:"Junior Development",bio:"Focuses on technique and young swimmers.",rating:4.8}],
swimmers:[
{id:101,name:"Omar Khaled",age:14,gender:"Male",phone:"0109 555 1111",level:"Advanced",coach:1,rating:4.9,stars:5,achievements:"National Junior Championship finalist",months:["August 2026"]},
{id:102,name:"Youssef Adel",age:12,gender:"Male",phone:"0108 222 3333",level:"Intermediate",coach:2,rating:4.6,stars:3,achievements:"50m freestyle medal",months:["August 2026"]},
{id:103,name:"Mariam Tarek",age:15,gender:"Female",phone:"0107 888 4444",level:"Advanced",coach:1,rating:4.8,stars:4,achievements:"Butterfly regional champion",months:[]}]};
let data=JSON.parse(localStorage.getItem(KEY)||"null")||defaultData;
if(!data.posts)data.posts=[];
function save(){localStorage.setItem(KEY,JSON.stringify(data))}
function isAdmin(){return sessionStorage.getItem("bw_admin")==="1"}
function requireAdmin(action){if(!isAdmin()){toast("Admin login required");return false}return true}
function go(p){if(["dashboard","swimmers","coaches"].includes(p)&&!isAdmin()){document.getElementById("loginScreen").style.display="grid";return}document.querySelectorAll(".page").forEach(x=>x.classList.remove("active"));const el=document.getElementById(p);if(el)el.classList.add("active");document.querySelectorAll(".nav").forEach(x=>x.classList.toggle("active",x.dataset.page===p));if(p==="dashboard")renderDashboard();if(p==="swimmers")renderSwimmers();if(p==="coaches")renderCoaches();if(p==="public")renderPublic();}
document.querySelectorAll(".nav").forEach(b=>b.onclick=()=>go(b.dataset.page));
function coach(id){return data.coaches.find(c=>c.id==id)}
function initials(n){return n.split(" ").map(x=>x[0]).slice(0,2).join("").toUpperCase()}
function currentMonth(){return data.months[data.months.length-1]}
function renderDashboard(){
let paid=data.swimmers.filter(s=>s.months.includes(currentMonth())).length;
document.getElementById("stats").innerHTML=`<div class="stat"><span>Total swimmers</span><strong>${data.swimmers.length}</strong></div><div class="stat"><span>Coaches</span><strong>${data.coaches.length}</strong></div><div class="stat"><span>Paid — ${currentMonth()}</span><strong>${paid}</strong></div><div class="stat"><span>Unpaid</span><strong>${data.swimmers.length-paid}</strong></div>`;
document.getElementById("paymentOverview").innerHTML=`<div class="mini"><b>Current month</b><span>${currentMonth()}</span></div><div class="mini"><b>Paid</b><span class="badge paid">${paid} swimmers</span></div><div class="mini"><b>Unpaid</b><span class="badge unpaid">${data.swimmers.length-paid} swimmers</span></div><div class="mini"><b>Months tracked</b><span>${data.months.length}</span></div>`;
document.getElementById("topSwimmers").innerHTML=[...data.swimmers].sort((a,b)=>b.rating-a.rating).slice(0,4).map((s,i)=>`<div class="mini"><span><b class="rank">#${i+1}</b> ${s.name}</span><span>⭐ ${s.rating}</span></div>`).join("")||'<div class="empty">No swimmers yet.</div>';
}
function populateFilters(){let c=document.getElementById("coachFilter");let v=c.value;c.innerHTML='<option value="">All coaches</option>'+data.coaches.map(x=>`<option value="${x.id}">${x.name}</option>`).join("");c.value=v}
function renderSwimmers(){
populateFilters();let q=(document.getElementById("search")?.value||"").toLowerCase(), cf=document.getElementById("coachFilter")?.value||"", pf=document.getElementById("paymentFilter")?.value||"";
let arr=data.swimmers.filter(s=>(s.name.toLowerCase().includes(q)||String(s.id).includes(q))&&(!cf||s.coach==cf)&&(!pf||(pf==="paid" ? s.months.includes(currentMonth()):!s.months.includes(currentMonth()))));
document.getElementById("swimmerTable").innerHTML=arr.length?`<table class="table"><thead><tr><th>Swimmer</th><th>Age / Level</th><th>Coach</th><th>Rating</th><th>Current payment</th><th></th></tr></thead><tbody>${arr.map(s=>`<tr><td><div class="namecell"><span class="avatar">${initials(s.name)}</span><div><b>${s.name}</b><small style="display:block;color:#8194a7">ID ${s.id}</small></div></div></td><td>${s.age} yrs · ${s.level}</td><td>${coach(s.coach)?.name||"Unassigned"}</td><td>⭐ ${s.rating}</td><td><span class="badge ${s.months.includes(currentMonth())?"paid":"unpaid"}">${s.months.includes(currentMonth())?"Paid":"Unpaid"}</span></td><td><button class="action" onclick="viewSwimmer(${s.id})">View</button> <button class="action" onclick="openSwimmer(${s.id})">Edit</button></td></tr>`).join("")}</tbody></table>`:'<div class="empty">No swimmers match your search.</div>';
}
function renderCoaches(){document.getElementById("coachGrid").innerHTML=data.coaches.map(c=>{let n=data.swimmers.filter(s=>s.coach==c.id).length;return `<div class="coach"><span class="avatar">${initials(c.name.replace("Coach ",""))}</span><h3>${c.name}</h3><p>${c.specialty}</p><div class="mini"><span>Rating</span><b>⭐ ${c.rating}</b></div><div class="mini"><span>Swimmers</span><b>${n}</b></div><p>${c.bio}</p><button class="action" onclick="openCoach(${c.id})">Edit coach</button></div>`}).join("")||'<div class="empty">No coaches yet.</div>'}
function renderPublic(){let q=(document.getElementById("publicSearch")?.value||"").toLowerCase();let arr=data.swimmers.filter(s=>s.name.toLowerCase().includes(q));document.getElementById("publicGrid").innerHTML=arr.map(s=>`<div class="swcard"><div class="bigavatar">${initials(s.name)}</div><h3>${s.name}</h3><p>${s.level} swimmer · ${s.age} years</p><div class="mini"><span>Coach</span><b>${coach(s.coach)?.name||"—"}</b></div><div class="mini"><span>Rating</span><b>⭐ ${s.rating}/5</b></div><div class="mini"><span>Stars</span><b class="stars">${"★".repeat(Math.min(5,s.stars))}${"☆".repeat(5-Math.min(5,s.stars))}</b></div><p><b>Achievement:</b> ${s.achievements||"—"}</p></div>`).join("")||'<div class="empty">No swimmers found.</div>'}
function openSwimmer(id=null){if(!requireAdmin("swimmer"))return;let s=id?data.swimmers.find(x=>x.id==id):null;document.getElementById("modalContent").innerHTML=`<h2>${s?"Edit swimmer":"Add swimmer"}</h2><form onsubmit="submitSwimmer(event,${id||0})"><div class="formgrid">
<div class="field"><label>Full name</label><input name="name" required value="${s?.name||""}"></div><div class="field"><label>Swimmer ID</label><input name="id" required value="${s?.id||""}" ${s?"readonly":""}></div>
<div class="field"><label>Age</label><input name="age" type="number" min="1" max="100" required value="${s?.age||""}"></div><div class="field"><label>Gender</label><select name="gender"><option ${s?.gender==="Male"?"selected":""}>Male</option><option ${s?.gender==="Female"?"selected":""}>Female</option></select></div>
<div class="field"><label>Phone</label><input name="phone" value="${s?.phone||""}"></div><div class="field"><label>Swimming level</label><select name="level"><option>Beginner</option><option ${s?.level==="Intermediate"?"selected":""}>Intermediate</option><option ${s?.level==="Advanced"?"selected":""}>Advanced</option><option>Elite</option></select></div>
<div class="field"><label>Coach</label><select name="coach"><option value="">Unassigned</option>${data.coaches.map(c=>`<option value="${c.id}" ${s?.coach==c.id?"selected":""}>${c.name}</option>`).join("")}</select></div><div class="field"><label>Rating (0–5)</label><input name="rating" type="number" step=".1" min="0" max="5" value="${s?.rating??5}"></div>
<div class="field"><label>Stars achieved (0–5)</label><input name="stars" type="number" min="0" max="5" value="${s?.stars??0}"></div><div class="field"><label>Achievements</label><input name="achievements" value="${s?.achievements||""}"></div>
<div class="field full"><label>Monthly payments — add new months in Coaches/Dashboard? Current months are managed here.</label><div class="months">${data.months.map(m=>`<label class="month ${s?.months.includes(m)?"on":""}"><input type="checkbox" name="months" value="${m}" ${s?.months.includes(m)?"checked":""}> ${m}</label>`).join("")}</div></div>
<div class="field full"><label>Add a new month</label><div style="display:flex;gap:8px"><input id="newMonth" placeholder="e.g. September 2026"><button type="button" class="secondary" onclick="addMonth()">Add month</button></div></div>
</div><div class="formactions"><button type="button" class="secondary" onclick="closeModal()">Cancel</button><button class="primary">Save swimmer</button></div></form>`;openModal()}
function addMonth(){if(!requireAdmin("month"))return;let x=document.getElementById("newMonth").value.trim();if(!x)return;if(!data.months.includes(x)){data.months.push(x);save();openSwimmer()}else toast("Month already exists")}
function submitSwimmer(e,id){if(!requireAdmin("swimmer"))return;e.preventDefault();let f=new FormData(e.target);let s=id?data.swimmers.find(x=>x.id==id):{id:Number(f.get("id")),months:[]};s.name=f.get("name");s.age=Number(f.get("age"));s.gender=f.get("gender");s.phone=f.get("phone");s.level=f.get("level");s.coach=Number(f.get("coach"))||null;s.rating=Number(f.get("rating"));s.stars=Number(f.get("stars"));s.achievements=f.get("achievements");s.months=[...f.getAll("months")];if(!id)data.swimmers.push(s);save();closeModal();renderDashboard();renderSwimmers();toast(id?"Swimmer updated":"Swimmer added")}
function viewSwimmer(id){let s=data.swimmers.find(x=>x.id==id);document.getElementById("modalContent").innerHTML=`<h2>${s.name}</h2><p style="color:#7890a8">ID ${s.id} · ${s.gender} · ${s.age} years</p><div class="detail"><div class="mini"><span>Coach</span><b>${coach(s.coach)?.name||"Unassigned"}</b></div><div class="mini"><span>Level</span><b>${s.level}</b></div><div class="mini"><span>Rating</span><b>⭐ ${s.rating}/5</b></div><div class="mini"><span>Stars</span><b class="stars">${"★".repeat(s.stars)}${"☆".repeat(5-s.stars)}</b></div><div class="mini"><span>Achievement</span><b>${s.achievements||"—"}</b></div></div><h3>Payment history</h3>${data.months.map(m=>`<div class="mini"><span>${m}</span><span class="badge ${s.months.includes(m)?"paid":"unpaid"}">${s.months.includes(m)?"Paid":"Unpaid"}</span></div>`).join("")}<div class="formactions"><button class="secondary" onclick="closeModal()">Close</button><button class="primary" onclick="closeModal();openSwimmer(${s.id})">Edit</button></div>`;openModal()}
function openCoach(id=null){if(!requireAdmin("coach"))return;let c=id?data.coaches.find(x=>x.id==id):null;document.getElementById("modalContent").innerHTML=`<h2>${c?"Edit coach":"Add coach"}</h2><form onsubmit="submitCoach(event,${id||0})"><div class="formgrid"><div class="field full"><label>Coach name</label><input name="name" required value="${c?.name||""}"></div><div class="field"><label>Phone</label><input name="phone" value="${c?.phone||""}"></div><div class="field"><label>Specialty</label><input name="specialty" value="${c?.specialty||""}"></div><div class="field"><label>Rating</label><input name="rating" type="number" min="0" max="5" step=".1" value="${c?.rating??5}"></div><div class="field full"><label>Bio</label><textarea name="bio" rows="3">${c?.bio||""}</textarea></div></div><div class="formactions"><button type="button" class="secondary" onclick="closeModal()">Cancel</button><button class="primary">Save coach</button></div></form>`;openModal()}
function submitCoach(e,id){if(!requireAdmin("coach"))return;e.preventDefault();let f=new FormData(e.target),c=id?data.coaches.find(x=>x.id==id):{id:Date.now()};c.name=f.get("name");c.phone=f.get("phone");c.specialty=f.get("specialty");c.rating=Number(f.get("rating"));c.bio=f.get("bio");if(!id)data.coaches.push(c);save();closeModal();renderCoaches();renderSwimmers();toast(id?"Coach updated":"Coach added")}
function openModal(){document.getElementById("modal").classList.remove("hidden")}function closeModal(){document.getElementById("modal").classList.add("hidden")}function toast(t){let x=document.getElementById("toast");x.textContent=t;x.classList.add("show");setTimeout(()=>x.classList.remove("show"),1800)}
renderDashboard();renderSwimmers();renderCoaches();renderPublic();checkAccess();updateAdminUI();
if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js");

let deferredInstallPrompt=null;
window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredInstallPrompt=e;const b=document.getElementById("installBtn");if(b)b.style.display="block"});
document.addEventListener("click",e=>{
 if(e.target && e.target.id==="installBtn"){
   if(deferredInstallPrompt){deferredInstallPrompt.prompt();deferredInstallPrompt.userChoice.finally(()=>{deferredInstallPrompt=null;e.target.style.display="none"})}
   else document.getElementById("installHelp").classList.remove("hidden");
 }
});
function closeInstallHelp(){document.getElementById("installHelp").classList.add("hidden")}

function showInstall(){document.getElementById("installHelp")?.classList.remove("hidden")}
function closeInstallHelp(){document.getElementById("installHelp")?.classList.add("hidden")}
function homeCards(arr){return arr.map(s=>`<div class="post card"><div class="posthead"><div class="profile"><div class="miniavatar">${initials(s.name)}</div><div><b>${s.name}</b><small>${s.level} · ${coach(s.coach)?.name||"No coach"}</small></div></div><span>•••</span></div><div style="padding:20px;background:linear-gradient(135deg,#e8f8ff,#d5ecff)"><div style="font-size:55px">🏊</div><h2>${s.name}</h2><p>${s.achievements||"Training hard and making waves!"}</p></div><div class="postactions">♡　💬　↗ <span class="save">⌑</span></div><b class="likes">⭐ ${s.rating}/5 · ${s.stars} stars</b><p><b>Coach:</b> ${coach(s.coach)?.name||"Unassigned"} · <b>Level:</b> ${s.level}</p></div>`).join("")||'<div class="card empty">No swimmers found.</div>'}
function renderSuggestions(arr=data.swimmers){let b=document.getElementById("suggestions");if(!b)return;b.innerHTML=arr.slice(0,4).map(s=>`<div class="suggestion"><div class="miniavatar">${initials(s.name)}</div><div class="sname"><b>${s.name}</b><small>${s.level}</small></div><button class="follow" onclick="viewSwimmer(${s.id})">View</button></div>`).join("")}
function homeSearch(q){let a=data.swimmers.filter(s=>s.name.toLowerCase().includes(q.toLowerCase()));document.getElementById("homeFeed").innerHTML=homeCards(a);renderSuggestions(a)}

function openPost(){
 if(!requireAdmin("post"))return;
 document.getElementById("modalContent").innerHTML=`<h2>＋ Create a post</h2><form onsubmit="submitPost(event)"><div class="formgrid"><div class="field full"><label>Post title</label><input name="title" required placeholder="e.g. Training Day"></div><div class="field full"><label>Post text</label><textarea name="text" rows="5" required placeholder="Write your swimming club update..."></textarea></div><div class="field"><label>Emoji / visual</label><input name="visual" value="🏊" maxlength="4"></div><div class="field"><label>Category</label><select name="category"><option>Training</option><option>Competition</option><option>Achievement</option><option>Announcement</option></select></div></div><div class="formactions"><button type="button" class="secondary" onclick="closeModal()">Cancel</button><button class="primary">Publish post</button></div></form>`;openModal()
}
function submitPost(e){if(!requireAdmin("post"))return;e.preventDefault();let f=new FormData(e.target);data.posts.unshift({id:Date.now(),title:f.get("title"),text:f.get("text"),visual:f.get("visual")||"🏊",category:f.get("category"),date:new Date().toLocaleDateString()});save();closeModal();renderHome();toast("Post published")}
function postCards(){return (data.posts||[]).map(p=>`<div class="post card"><div class="posthead"><div class="profile"><div class="miniavatar">${p.visual}</div><div><b>bluewave.swimming</b><small>${p.category} · ${p.date}</small></div></div>${isAdmin()?`<button class="dots" onclick="deletePost(${p.id})">🗑</button>`:""}</div><div class="club-post"><span>${p.visual}</span><h2>${p.title}</h2><p>${p.text}</p></div><div class="postactions">♡　💬　↗ <span class="save">⌑</span></div><b class="likes">BlueWave Swimming Club</b></div>`).join("")
}
function deletePost(id){if(!requireAdmin("post"))return;if(confirm("Delete this post?")){data.posts=data.posts.filter(p=>p.id!==id);save();renderHome();toast("Post deleted")}}

function renderHome(){document.getElementById("homeFeed").innerHTML=postCards()+homeCards(data.swimmers.slice(0,3));renderSuggestions()}
renderHome();

function updateAdminUI(){const a=isAdmin();const b=document.getElementById("adminPostBtn");if(b)b.style.display=a?"block":"none"}
